{{- if .Values.global.oidc_key_reader_role_arn }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: rc-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.aws_region }}
      role: "{{ .Values.global.oidc_key_reader_role_arn }}"
{{- end }}
